import { ArrowLeft, ArrowRight, CircleUserRound, Heart, LogOut, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

export default function AccountPage() {
  const { user, isAuthenticated, loading, logout } = useAuth();
  if (loading) return <div className="page-loading">Loading your account…</div>;
  if (!isAuthenticated) return <div className="empty-page"><CircleUserRound size={28} className="text-[#b47d22]" /><h1 className="mt-5 font-display text-5xl">Your sourcing desk.</h1><p className="mt-4 max-w-md text-sm leading-7 text-[#6b716f]">Sign in to save products, manage your buying brief, and keep your sourcing decisions in one place.</p><button className="button-primary mt-7" onClick={() => startLogin()}>Sign in to continue <ArrowRight size={16} /></button></div>;
  return <div className="mx-auto max-w-[1000px] px-5 py-16 lg:px-10 lg:py-24"><Link href="/" className="back-link"><ArrowLeft size={15} /> Back to marketplace</Link><div className="mt-12 grid gap-8 md:grid-cols-[1fr_1.2fr]"><section className="rounded-2xl bg-[#0b1830] p-8 text-white"><CircleUserRound size={28} className="text-amber-200" /><p className="eyebrow mt-8 text-amber-200">Buyer account</p><h1 className="mt-4 font-display text-5xl leading-none">Welcome back.</h1><p className="mt-5 text-sm leading-7 text-white/65">{user?.email ?? "Authenticated buyer"}</p><button className="mt-8 inline-flex items-center gap-2 text-sm text-amber-200" onClick={() => void logout()}><LogOut size={15} /> Sign out</button></section><section className="rounded-2xl border border-[#e5e1d9] bg-white p-8"><p className="eyebrow text-[#b47d22]">Your workspace</p><h2 className="mt-4 font-display text-4xl">Keep the next run moving.</h2><div className="mt-8 grid gap-4"><Link href="/saved" className="flex items-center justify-between rounded-xl border border-[#e5e1d9] p-5 transition hover:border-[#b47d22]"><span className="flex items-center gap-3"><Heart size={18} className="text-[#b47d22]" /><span><strong className="block">Saved products</strong><small className="text-[#6b716f]">Return to your shortlist</small></span></span><ArrowRight size={16} /></Link><div className="flex items-center gap-3 rounded-xl bg-[#f3f0e9] p-5"><ShieldCheck size={18} className="text-[#b47d22]" /><span><strong className="block">Secure buyer identity</strong><small className="text-[#6b716f]">Your saved products are linked to this account.</small></span></div></div></section></div></div>;
}
